
#include "ja.h"
#include "jae.h"
#include "jb.h"
#include "jbe.h"
#include "jg.h"
#include "jge.h"
#include "jl.h"
#include "jle.h"
#include "je.h"
#include "jne.h"
#include "jo.h"
#include "jno.h"
#include "jp.h"
#include "jnp.h"
#include "js.h"
#include "jns.h"
